import fs from 'node:fs';
import vm from 'node:vm';
const assert=(cond,msg)=>{if(!cond){console.error('FAIL:',msg);process.exitCode=1}else console.log('PASS:',msg)};
const index=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const data=fs.readFileSync(new URL('../data.js',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
for(const id of ['home','study','battle','records','settings','result','difficultySelect','countSelect','questionText','choices','answerInput'])assert(index.includes(`id="${id}"`),`HTML id ${id}`);
const sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(data,sandbox);
const qs=sandbox.window.ERP_HR_QUESTIONS||[], chapters=sandbox.window.ERP_HR_CHAPTERS||[], cards=sandbox.window.ERP_HR_STUDY_CARDS||[];
assert(qs.length===120,'문제 120개');assert(chapters.length===12,'챕터 12개');assert(cards.length>=100,'학습 카드 100개 이상');assert(new Set(qs.map(q=>q.id)).size===qs.length,'문항 ID 중복 없음');assert(qs.every(q=>[1,2,3].includes(q.difficulty)),'난이도 1~3');assert(qs.filter(q=>q.type==='4지선다').every(q=>q.options.includes(q.answer)),'객관식 정답이 보기 안에 존재');assert(app.includes('window.__ERP_HR_GUILD_READY__=true'),'준비 플래그 존재');
if(!process.exitCode)console.log('검수 완료');
