/* ERP 인사 길드 v1.0 */
(function(){
'use strict';
const $=id=>document.getElementById(id);
window.addEventListener('error',()=>{const e=$('fatalError');if(e)e.hidden=false});
window.addEventListener('unhandledrejection',()=>{const e=$('fatalError');if(e)e.hidden=false});
const CHAPTERS=window.ERP_HR_CHAPTERS||[];
const QUESTION_BANK=window.ERP_HR_QUESTIONS||[];
const STUDY_CARDS=window.ERP_HR_STUDY_CARDS||[];
const SAVE_KEY='erpHrGuildV1';
const ENEMIES=[['개념 슬라임','🟢'],['암기 고블린','👺'],['규정 미믹','📦'],['세율 마도서','📕'],['노사 드래곤','🐉']];
const defaultPlayer={level:1,xp:0,gold:0,total:0,correct:0,bestCombo:0,todayDate:'',todayCount:0,wrongIds:[],chapterStats:{},recent:[],settings:{autoRetry:true,vibration:true,fontScale:'1'}};
let player=loadPlayer();
let studyTab='summary',flashIndex=0,flashFlipped=false,lastMode='mixed';
let battle=null,calcExpression='';

function safeParse(text,fallback){try{return JSON.parse(text)}catch{return fallback}}
function loadPlayer(){const raw=localStorage.getItem(SAVE_KEY);const saved=raw?safeParse(raw,{}):{};return {...defaultPlayer,...saved,settings:{...defaultPlayer.settings,...(saved.settings||{})},wrongIds:Array.isArray(saved.wrongIds)?saved.wrongIds:[],chapterStats:saved.chapterStats||{},recent:Array.isArray(saved.recent)?saved.recent:[]}}
function savePlayer(){localStorage.setItem(SAVE_KEY,JSON.stringify(player))}
function todayKey(){return new Date().toISOString().slice(0,10)}
function updateToday(){const key=todayKey();if(player.todayDate!==key){player.todayDate=key;player.todayCount=0}}
function shuffle(a){const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function normalize(s){return String(s??'').toLowerCase().normalize('NFKC').replace(/\s+/g,'').replace(/[.,·:;()\[\]{}\-_/＝=]/g,'')}
function parseNumeric(text){let s=String(text??'').replace(/,/g,'').trim();if(!s)return NaN;let multiplier=1;if(/만원/.test(s)||/만\s*원/.test(s)||/만$/.test(s))multiplier=10000;else if(/천원/.test(s))multiplier=1000;const m=s.match(/-?\d+(?:\.\d+)?/);return m?Number(m[0])*multiplier:NaN}
function answerMatches(q,input){const n=normalize(input);if(!n)return false;const candidates=[q.answer,...(q.aliases||[])];if(candidates.some(a=>normalize(a)===n))return true;
 if(q.answer==='O')return ['o','맞다','참','true'].includes(String(input).trim().toLowerCase());
 if(q.answer==='X')return ['x','틀리다','거짓','false'].includes(String(input).trim().toLowerCase());
 const targetNum=parseNumeric(q.answer),inputNum=parseNumeric(input);if(Number.isFinite(targetNum)&&Number.isFinite(inputNum)&&Math.abs(targetNum-inputNum)<0.0001)return true;
 if(q.answer.includes(',')){const tokens=q.answer.split(',').map(normalize).filter(Boolean);return tokens.length>1&&tokens.every(t=>n.includes(t))}
 return false}
function calcMatches(q,input){const v=parseNumeric(input);if(!Number.isFinite(v))return false;return Math.abs(v-q.numericAnswer)<=Math.max(0.5,Math.abs(q.numericAnswer)*0.00001)}
function toast(text){const t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1400)}
function vibrate(pattern){if(player.settings.vibration&&navigator.vibrate)navigator.vibrate(pattern)}
function rankFor(level){if(level>=16)return['ERP 인사 마스터','🧙‍♂️'];if(level>=12)return['인사팀 부장','🧑‍💼'];if(level>=8)return['인사팀 과장','🧑‍💻'];if(level>=5)return['인사팀 대리','🧑‍🏫'];if(level>=3)return['인사팀 주임','🧑‍🔧'];return['신입 사원','🧑‍💼']}
function xpNeeded(level){return 80+level*35}
function addXp(amount){player.xp+=amount;while(player.xp>=xpNeeded(player.level)){player.xp-=xpNeeded(player.level);player.level++;toast(`레벨 업! Lv.${player.level}`)}}
function updateHeader(){updateToday();const [rank]=rankFor(player.level);$('miniLevel').textContent=player.level;$('miniGold').textContent=player.gold;$('rankName').textContent=rank;$('miniXp').style.width=(player.xp/xpNeeded(player.level)*100)+'%';$('todayHome').textContent=player.todayCount+'문제';$('overallHome').textContent=(player.total?Math.round(player.correct/player.total*100):0)+'%';$('wrongHome').textContent=player.wrongIds.length+'개';$('wrongTag').textContent=player.wrongIds.length+'개';document.documentElement.style.setProperty('--qscale',player.settings.fontScale)}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));if(id==='home')renderHome();if(id==='study')renderStudy();if(id==='records')renderRecords();if(id==='settings')renderSettings();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));
document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>showScreen('home'));
$('openSettingsTop').onclick=()=>showScreen('settings');

function chapterQuestionCount(id){return QUESTION_BANK.filter(q=>q.chapterId===id).length}
function renderHome(){updateHeader();$('chapterGrid').innerHTML=CHAPTERS.map(c=>{const s=player.chapterStats[c.id]||{total:0,correct:0};const acc=s.total?Math.round(s.correct/s.total*100):0;return `<button class="chapter-card" data-chapter="${c.id}"><span class="tag">${acc}%</span><div class="icon">${c.icon}</div><h3>${escapeHtml(c.title)}</h3><p>${escapeHtml(c.summary)}</p><div class="chapter-meta"><span>${chapterQuestionCount(c.id)}문항</span><span>PDF p.${c.pages[0]}-${c.pages[c.pages.length-1]}</span></div></button>`}).join('');document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>startBattle('chapter',b.dataset.chapter));const learned=CHAPTERS.filter(c=>(player.chapterStats[c.id]?.total||0)>0).length;$('chapterProgressText').textContent=`${learned}/12 학습`}

document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>startBattle(b.dataset.mode));
function selectedDifficulty(){return $('difficultySelect').value}
function selectedCount(){return Number($('countSelect').value)}
function filterByDifficulty(pool){const d=selectedDifficulty();return d==='all'?pool:pool.filter(q=>q.difficulty===Number(d))}
function toSubjective(q,retry=false){return {...q,id:(retry?'R_':'S_')+q.id,kind:retry?'오답 재도전 · 주관식':'주관식',options:[],input:true,isRetry:retry,baseId:q.id}}
function questionCopy(q){return {...q,options:[...(q.options||[])],aliases:[...(q.aliases||[])]}}
function buildQuestions(mode,chapterId){let pool=[];const count=mode==='final'?30:selectedCount();if(mode==='chapter')pool=QUESTION_BANK.filter(q=>q.chapterId===chapterId);else if(mode==='objective')pool=QUESTION_BANK.filter(q=>q.type!=='단답형');else if(mode==='subjective')pool=QUESTION_BANK;else if(mode==='mixed')pool=QUESTION_BANK;else if(mode==='wrong'){const set=new Set(player.wrongIds);pool=QUESTION_BANK.filter(q=>set.has(q.id));if(!pool.length)return[]}else if(mode==='final')pool=QUESTION_BANK;
 if(mode==='calculation')return buildCalculationQuestions(count);
 if(mode!=='final')pool=filterByDifficulty(pool);if(!pool.length)return[];let picked=shuffle(pool).slice(0,Math.min(count,pool.length)).map(questionCopy);
 if(mode==='subjective')picked=picked.map(q=>toSubjective(q));
 if(mode==='mixed'||mode==='chapter'||mode==='final')picked=picked.map((q,i)=>i%3===2?toSubjective(q):q);
 if(mode==='wrong')picked=picked.map(q=>toSubjective(q));return picked}
function enemyFor(mode,chapterId){if(mode==='calculation')return['세율 마도서','📕'];if(mode==='wrong')return['오답 망령','👻'];if(mode==='final')return['노사 드래곤','🐉'];if(mode==='chapter'){const c=CHAPTERS.find(x=>x.id===chapterId);return[c?.title+' 수문장',c?.icon||'👾']}return ENEMIES[Math.floor(Math.random()*ENEMIES.length)]}
function startBattle(mode,chapterId){const qs=buildQuestions(mode,chapterId);if(!qs.length){alert(mode==='wrong'?'복습할 오답이 없어. 먼저 퀴즈를 풀어 줘.':'선택한 조건에 맞는 문제가 없어. 난이도를 바꿔 줘.');return}lastMode=mode;const enemy=enemyFor(mode,chapterId);const maxHp=Math.max(100,qs.length*20);battle={mode,chapterId,questions:qs,index:0,correct:0,score:0,combo:0,maxCombo:0,answered:false,playerHp:100,maxPlayer:100,enemyHp:maxHp,maxEnemy:maxHp,enemy,retryIds:new Set(),results:[]};$('enemyName').textContent=enemy[0];$('enemyFace').textContent=enemy[1];$('battleTotal').textContent=qs.length;showScreen('battle');renderBattle()}

function renderBattle(){const q=battle.questions[battle.index];battle.answered=false;calcExpression='';$('feedback').className='feedback';$('feedback').innerHTML='';$('nextQuestion').hidden=true;$('battleNumber').textContent=battle.index+1;$('battleTotal').textContent=battle.questions.length;$('battleCombo').textContent=battle.combo;$('battleScore').textContent=battle.score;$('playerHpBar').style.width=(battle.playerHp/battle.maxPlayer*100)+'%';$('enemyHpBar').style.width=(battle.enemyHp/battle.maxEnemy*100)+'%';$('playerHpText').textContent=`${battle.playerHp}/${battle.maxPlayer}`;$('enemyHpText').textContent=`${Math.max(0,battle.enemyHp)}/${battle.maxEnemy}`;$('qType').textContent=(q.kind||q.type)+(q.isRetry?' · 오답 재도전':'');$('qSource').textContent=`PDF p.${q.page}`;$('questionText').textContent=q.prompt;$('formulaHint').hidden=!q.formula;$('formulaHint').textContent=q.formula||'';$('choices').innerHTML='';$('inputRow').hidden=true;$('calcPanel').hidden=!q.calculator;
 if(q.calculator)renderCalculator();
 const inputMode=q.input||q.type==='단답형'||q.calculator;
 if(inputMode){$('inputRow').hidden=false;$('answerInput').value='';$('answerInput').placeholder=q.placeholder||'정답 입력';setTimeout(()=>$('answerInput').focus({preventScroll:true}),80)}else{const options=q.options||[];$('choices').innerHTML=options.map((o,i)=>`<button class="choice" data-option="${i}">${escapeHtml(o)}</button>`).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>submitCurrent((q.options||[])[Number(b.dataset.option)],b))}}
function renderCalculator(){const keys=['7','8','9','÷','4','5','6','×','1','2','3','-','0','.','C','+'];$('calcGrid').innerHTML=keys.map(k=>`<button class="calc-key" data-key="${k}">${k}</button>`).join('')+'<button class="calc-key eq" data-key="=" style="grid-column:span 4">=</button>';$('calcDisplay').value='';document.querySelectorAll('.calc-key').forEach(b=>b.onclick=()=>calcKey(b.dataset.key))}
function calcKey(k){if(k==='C')calcExpression='';else if(k==='='){try{calcExpression=String(Function('return ('+calcExpression.replace(/×/g,'*').replace(/÷/g,'/')+')')())}catch{toast('계산식을 확인해 줘')}}else calcExpression+=k;$('calcDisplay').value=calcExpression}
$('copyCalc').onclick=()=>{if(!calcExpression)return;if(/[+\-×÷]/.test(calcExpression)){calcKey('=')}$('answerInput').value=calcExpression;$('answerInput').focus()};
$('submitAnswer').onclick=()=>submitCurrent($('answerInput').value,null);
$('answerInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!battle?.answered){e.preventDefault();submitCurrent(e.currentTarget.value,null)}});
$('answerInput').addEventListener('focus',e=>setTimeout(()=>e.target.scrollIntoView({block:'center',behavior:'smooth'}),180));
function addWrong(id){if(!player.wrongIds.includes(id))player.wrongIds.push(id)}
function removeWrong(id){player.wrongIds=player.wrongIds.filter(x=>x!==id)}
function scheduleRetry(q){const baseId=q.baseId||q.id;if(!player.settings.autoRetry||q.isRetry||battle.retryIds.has(baseId))return false;battle.retryIds.add(baseId);let retry;if(q.calculator){retry={...q,id:'R_'+q.id,isRetry:true,kind:'오답 재도전 · 계산'}}else{const source=QUESTION_BANK.find(x=>x.id===baseId);if(!source)return false;retry=toSubjective(questionCopy(source),true)}const at=Math.min(battle.questions.length,battle.index+4);battle.questions.splice(at,0,retry);return true}
function updateChapterStat(q,ok){if(!q.chapterId)return;const s=player.chapterStats[q.chapterId]||{total:0,correct:0};s.total++;if(ok)s.correct++;player.chapterStats[q.chapterId]=s}
function submitCurrent(input,button){if(!battle||battle.answered)return;const q=battle.questions[battle.index];const ok=q.calculator?calcMatches(q,input):answerMatches(q,input);battle.answered=true;player.total++;player.todayCount++;if(ok){player.correct++;battle.correct++;battle.combo++;battle.maxCombo=Math.max(battle.maxCombo,battle.combo);battle.score+=100+battle.combo*10;battle.enemyHp=Math.max(0,battle.enemyHp-20);removeWrong(q.baseId||q.id);vibrate(35)}else{battle.combo=0;battle.playerHp=Math.max(0,battle.playerHp-Math.max(4,Math.floor(80/battle.questions.length)));if(!q.calculator)addWrong(q.baseId||q.id);vibrate([50,45,70])}player.bestCombo=Math.max(player.bestCombo,battle.maxCombo);updateChapterStat(q,ok);battle.results.push({id:q.baseId||q.id,ok,answer:String(input),correct:q.answer,chapterId:q.chapterId});player.recent.unshift({id:q.baseId||q.id,ok,prompt:q.prompt,answer:String(input),correct:q.answer,time:new Date().toISOString()});player.recent=player.recent.slice(0,10);
 if(button){document.querySelectorAll('.choice').forEach(b=>b.disabled=true);button.classList.add(ok?'correct':'wrong');if(!ok){document.querySelectorAll('.choice').forEach(b=>{if(normalize(b.textContent)===normalize(q.answer))b.classList.add('correct')})}}
 const retried=!ok&&scheduleRetry(q);$('feedback').className='feedback '+(ok?'good':'bad');$('feedback').innerHTML=`<b>${ok?'정답!':'오답'}</b><div class="answer-compare"><div class="answer-box"><small>내 답</small>${escapeHtml(input||'(미입력)')}</div><div class="answer-box"><small>정답</small>${escapeHtml(q.answer)}</div></div><div>${escapeHtml(q.explanation||'')}</div>${q.solution?`<div class="solution"><b>풀이</b><br>${escapeHtml(q.solution)}</div>`:''}${retried?'<div class="retry-note">이 문제는 약 3문제 뒤 주관식으로 다시 나와.</div>':''}`;$('nextQuestion').hidden=false;$('battleCombo').textContent=battle.combo;$('battleScore').textContent=battle.score;$('playerHpBar').style.width=(battle.playerHp/battle.maxPlayer*100)+'%';$('enemyHpBar').style.width=(battle.enemyHp/battle.maxEnemy*100)+'%';$('playerHpText').textContent=`${battle.playerHp}/${battle.maxPlayer}`;$('enemyHpText').textContent=`${battle.enemyHp}/${battle.maxEnemy}`;savePlayer();updateHeader()}
$('nextQuestion').onclick=()=>{if(battle.index+1>=battle.questions.length)finishBattle();else{battle.index++;renderBattle();window.scrollTo({top:0,behavior:'smooth'})}};
$('quitBattle').onclick=()=>{if(confirm('현재 퀘스트를 끝내고 나갈까?'))showScreen('home')};
function finishBattle(){const total=battle.results.length||battle.questions.length;const rate=Math.round(battle.correct/Math.max(1,total)*100);const clear=rate>=70;const xp=Math.max(10,battle.correct*8+(clear?20:0));const gold=Math.max(3,battle.correct*3+(clear?10:0));addXp(xp);player.gold+=gold;savePlayer();$('resultIcon').textContent=clear?'🏆':'📚';$('resultTitle').textContent=clear?'퀘스트 클리어!':'조금만 더 복습!';$('resultDesc').textContent=`${total}문제 중 ${battle.correct}문제 정답 · 정답률 ${rate}% · 최고 콤보 ${battle.maxCombo}`;$('rewardXp').textContent=xp;$('rewardGold').textContent=gold;showScreen('result');updateHeader()}
$('retryMode').onclick=()=>startBattle(lastMode,battle?.chapterId);

function rand(min,max,step=1){return min+Math.floor(Math.random()*((max-min)/step+1))*step}
function calcQ(id,prompt,answer,formula,solution,page,chapterId='tax',unit='원'){return{id:'CALC_'+id+'_'+Date.now()+'_'+Math.random(),baseId:'CALC_'+id,type:'계산',kind:'계산 문제',difficulty:2,prompt,answer:formatNumber(answer)+(unit||''),aliases:[],numericAnswer:answer,explanation:'PDF의 공식과 수치를 적용하는 계산 문제다.',solution,page,chapterId,options:[],input:true,calculator:true,formula,placeholder:`숫자 또는 ${unit} 단위로 입력`}}
function formatNumber(v){return Number(v).toLocaleString('ko-KR')}
function buildCalculationQuestions(count){const makers=[
 [1,()=>{const days=rand(89,92),daily=rand(80000,160000,5000),total=days*daily;return calcQ('AVG',`사유 발생 전 3개월의 임금총액이 ${formatNumber(total)}원이고 그 기간의 총일수가 ${days}일이다. 1일 평균임금은?`,daily,'평균임금 = 사유 발생 전 3개월 임금총액 ÷ 그 기간 총일수',`${formatNumber(total)} ÷ ${days} = ${formatNumber(daily)}원`,27,'wage')}],
 [1,()=>{const gross=rand(5000,12000,500),expense=rand(1000,gross-1000,500),ans=gross-expense;return calcQ('INCOME',`총수입금액이 ${formatNumber(gross)}만원, 필요경비가 ${formatNumber(expense)}만원일 때 소득금액은?`,ans*10000,'소득금액 = 총수입금액 - 필요경비',`${formatNumber(gross)} - ${formatNumber(expense)} = ${formatNumber(ans)}만원`,31,'tax')}],
 [2,()=>{const income=rand(4000,9000,500),ded=rand(500,2500,500),ans=income-ded;return calcQ('BASE',`종합소득금액이 ${formatNumber(income)}만원이고 종합소득공제가 ${formatNumber(ded)}만원일 때 종합소득 과세표준은?`,ans*10000,'종합소득 과세표준 = 종합소득금액 - 종합소득공제',`${formatNumber(income)} - ${formatNumber(ded)} = ${formatNumber(ans)}만원`,31,'tax')}],
 [3,()=>{const daily=rand(180000,450000,10000),base=daily-150000,tax=base*0.06,credit=tax*0.55,ans=Math.round(tax-credit);return calcQ('DAYTAX',`일용근로자의 일급여액이 ${formatNumber(daily)}원이다. PDF 공식에 따른 원천징수세액은?`,ans,'원천징수세액 = (일급여액 - 150,000원) × 6% - (산출세액 × 55%)',`과세대상 ${formatNumber(base)}원 × 6% = ${formatNumber(tax)}원, 세액공제 ${formatNumber(credit)}원, 최종 ${formatNumber(ans)}원`,32,'tax')}],
 [1,()=>{const people=rand(1,7),ans=people*1500000;return calcQ('BASIC',`기본공제 대상자가 ${people}명일 때 기본공제액은?`,ans,'기본공제액 = 기본공제 대상자 수 × 150만원',`${people} × 150만원 = ${formatNumber(ans/10000)}만원`,33,'tax')}],
 [2,()=>{const n=rand(1,6),ans=n===1?250000:n===2?550000:550000+(n-2)*400000;return calcQ('CHILD',`8세 이상 기본공제 대상 자녀가 ${n}명일 때 자녀세액공제액은?`,ans,'1명 25만원, 2명 55만원, 3명 이상은 55만원 + 2명 초과 1명당 40만원',n<=2?`${n}명 기준 ${formatNumber(ans/10000)}만원`:`55만원 + (${n}-2)×40만원 = ${formatNumber(ans/10000)}만원`,34,'tax')}],
 [3,()=>{const tax=rand(300,900,100),foreign=rand(20,60,10),total=100,ans=tax*foreign/total;return calcQ('FOREIGN',`산출세액이 ${tax}만원, 국외원천소득이 ${foreign}만원, 종합소득금액이 ${total}만원일 때 외국납부세액공제 한도액은?`,ans*10000,'한도액 = 산출세액 × 국외원천소득 ÷ 종합소득금액',`${tax} × ${foreign} ÷ ${total} = ${ans}만원`,33,'tax')}]
 ];const selected=selectedDifficulty();const available=selected==='all'?makers:makers.filter(([d])=>d===Number(selected));const out=[];for(let i=0;i<count;i++){const [difficulty,make]=available[i%available.length];const q=make();q.difficulty=difficulty;out.push(q)}return shuffle(out)}

function renderStudy(){document.querySelectorAll('[data-study-tab]').forEach(b=>b.classList.toggle('active',b.dataset.studyTab===studyTab));$('studySummary').hidden=studyTab!=='summary';$('studyCards').hidden=studyTab!=='cards';$('studyFlash').hidden=studyTab!=='flash';if(studyTab==='summary')renderSummaries();if(studyTab==='cards')renderTermCards();if(studyTab==='flash')renderFlash()}
document.querySelectorAll('[data-study-tab]').forEach(b=>b.onclick=()=>{studyTab=b.dataset.studyTab;renderStudy()});
function renderSummaries(){$('studySummary').innerHTML=CHAPTERS.map(c=>`<article class="chapter-note" style="margin-top:10px"><small>${c.part} · PDF p.${c.pages[0]}-${c.pages[c.pages.length-1]}</small><h3>${c.icon} ${escapeHtml(c.title)}</h3><p>${escapeHtml(c.summary)}</p><ul>${c.bullets.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul><button class="btn outline" data-summary-chapter="${c.id}">이 챕터 문제 풀기</button></article>`).join('');document.querySelectorAll('[data-summary-chapter]').forEach(b=>b.onclick=()=>startBattle('chapter',b.dataset.summaryChapter))}
function renderTermCards(){const search=normalize($('termSearch').value),chapter=$('chapterFilter').value;const cards=STUDY_CARDS.filter(c=>(chapter==='all'||c.chapterId===chapter)&&(!search||normalize(c.term+c.answer+c.meaning).includes(search)));$('termCards').innerHTML=cards.map(c=>`<article class="study-card"><small>PDF p.${c.page}</small><h3>${escapeHtml(c.term)}</h3><div class="answer">${escapeHtml(c.answer)}</div><p>${escapeHtml(c.meaning)}</p></article>`).join('')||'<div class="empty">검색 결과가 없어.</div>'}
$('termSearch').oninput=renderTermCards;$('chapterFilter').onchange=renderTermCards;
function renderFlash(){const c=STUDY_CARDS[flashIndex%STUDY_CARDS.length];$('flashCard').innerHTML=flashFlipped?`<div class="flash-back"><b>${escapeHtml(c.answer)}</b><br><br>${escapeHtml(c.meaning)}<div class="flash-hint">PDF p.${c.page} · 눌러서 앞면 보기</div></div>`:`<div class="flash-front">${escapeHtml(c.term)}</div><div class="flash-hint">눌러서 정답·설명 보기</div>`}
$('flashCard').onclick=$('flipFlash').onclick=()=>{flashFlipped=!flashFlipped;renderFlash()};$('prevFlash').onclick=()=>{flashIndex=(flashIndex-1+STUDY_CARDS.length)%STUDY_CARDS.length;flashFlipped=false;renderFlash()};$('nextFlash').onclick=()=>{flashIndex=(flashIndex+1)%STUDY_CARDS.length;flashFlipped=false;renderFlash()};

function renderRecords(){updateHeader();$('recordRank').textContent=`Lv.${player.level} ${rankFor(player.level)[0]}`;$('statAnswered').textContent=player.total;$('statAccuracy').textContent=(player.total?Math.round(player.correct/player.total*100):0)+'%';$('statCombo').textContent=player.bestCombo;$('statWrong').textContent=player.wrongIds.length;$('chapterStats').innerHTML=CHAPTERS.map(c=>{const s=player.chapterStats[c.id]||{total:0,correct:0};const acc=s.total?Math.round(s.correct/s.total*100):0;return `<div class="list-item"><div style="display:flex;justify-content:space-between"><b>${c.icon} ${escapeHtml(c.title)}</b><span>${s.correct}/${s.total} · ${acc}%</span></div><div class="bar"><div style="width:${acc}%"></div></div></div>`}).join('');const wrongQs=player.wrongIds.map(id=>QUESTION_BANK.find(q=>q.id===id)).filter(Boolean);$('wrongList').innerHTML=wrongQs.map(q=>`<div class="list-item"><b>${q.id} · ${escapeHtml(q.keyword)}</b><small>${escapeHtml(q.prompt)} · PDF p.${q.page}</small></div>`).join('')||'<div class="empty">남아 있는 오답이 없어.</div>';$('recentList').innerHTML=player.recent.map(r=>`<div class="list-item"><b>${r.ok?'✅':'❌'} ${escapeHtml(r.prompt)}</b><small>내 답: ${escapeHtml(r.answer||'(미입력)')} · 정답: ${escapeHtml(r.correct)}</small></div>`).join('')||'<div class="empty">아직 풀이 기록이 없어.</div>'}
$('clearWrong').onclick=()=>{if(confirm('오답 목록을 모두 비울까?')){player.wrongIds=[];savePlayer();renderRecords();updateHeader()}};

function renderSettings(){$('autoRetry').checked=player.settings.autoRetry;$('vibration').checked=player.settings.vibration;$('fontScale').value=player.settings.fontScale}
$('autoRetry').onchange=e=>{player.settings.autoRetry=e.target.checked;savePlayer()};$('vibration').onchange=e=>{player.settings.vibration=e.target.checked;savePlayer()};$('fontScale').onchange=e=>{player.settings.fontScale=e.target.value;savePlayer();updateHeader()};
$('backupSave').onclick=()=>{const blob=new Blob([JSON.stringify(player,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='erp-hr-guild-backup.json';a.click();URL.revokeObjectURL(a.href)};$('restoreSave').onclick=()=>$('restoreInput').click();$('restoreInput').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());player={...defaultPlayer,...data,settings:{...defaultPlayer.settings,...(data.settings||{})}};savePlayer();updateHeader();toast('복원 완료')}catch{alert('올바른 백업 파일이 아니야.')}};$('resetSave').onclick=()=>{if(confirm('모든 학습 기록을 초기화할까?')){localStorage.removeItem(SAVE_KEY);player={...defaultPlayer,wrongIds:[],chapterStats:{},recent:[],settings:{...defaultPlayer.settings}};savePlayer();updateHeader();showScreen('home')}};

// 초기화
$('chapterFilter').innerHTML='<option value="all">전체 챕터</option>'+CHAPTERS.map(c=>`<option value="${c.id}">${c.title}</option>`).join('');
updateToday();updateHeader();renderHome();renderStudy();
window.__ERP_HR_GUILD_READY__=true;const fatal=$('fatalError');if(fatal)fatal.hidden=true;
})();
